name: ambershellfish
description: Amber Shellfish
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.1.14
  cloud_functions: ^3.2.14
  flutter_native_splash: ^2.1.6
  go_router: ^3.1.0
  shared_preferences: ^2.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.otf
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
# run: $ flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#745B1A"
  image: images/logo.png
  color_dark: "#745B1A"
